server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
storage:
  local:
    upload-path: uploads/licenses
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/users_db?options=-c%20TimeZone=Asia/Kolkata
    username: postgres
    password: vasanth

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
jwt:
  secret: c2VjdXJlLWJhc2U2NC1lbmNvZGVkLWtleS1mb3ItcmlkZWxvb3AtMjU2LWJpdHMtMTIzNDU2Nzg5MA==
  expiration: 86400000

springdoc:

  swagger-ui:
    path: /swagger-ui.html


verification:
  otp:
    ttl: 300

  registration:
    ttl: 1800