server:
  port: ${PORT:8084}

spring:
  application:
    name: matching-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
  instance:
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name}:${server.port}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

matching:
  pickup-radius-km: 5.0

jwt:
  secret: ${JWT_SECRET}

trip:
  service:
    url: ${TRIP_SERVICE_URL:http://trip-service:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true