server:
  port: 8087

spring:
  application:
    name: ride-tracking-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/tracking_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:public}

  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      group-id: ride-tracking-service
      auto-offset-reset: earliest

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: ${JWT_SECRET}

trip:
  service:
    url: ${TRIP_SERVICE_URL:http://trip-service:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true