server:
  port: 8087

spring:
  application:
    name: ride-tracking-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tracking_db
    username: postgres
    password: vasanth

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: ride-tracking-service
      auto-offset-reset: earliest

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: c2VjdXJlLWJhc2U2NC1lbmNvZGVkLWtleS1mb3ItcmlkZWxvb3AtMjU2LWJpdHMtMTIzNDU2Nzg5MA==

trip:
  service:
    url: ${TRIP_SERVICE_URL:http://localhost:8082}


springdoc:


  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true